defaults:
  - _default
  - _self_

data:
  dataset: pdb
  rectify: True

  sampler:
    max_batch_size: 4
    max_num_res_squared: 500000

experiment:
  is_training: True
  debug: False
  num_devices: 1
  warm_start: ./ckpts/reqflow/reqflow_train_pdb_base/2025-12-04_14-36-56/last.ckpt # path to qflow ckpt which needs to be rectified
  warm_start_cfg_override: True
  resume_cfg_path: null
  resume_ckpt_path: null
  resume: False
  training:
    aux_loss_t_pass: 0.50
  wandb:
    name: reqflow_train_pdb_rectify
    project: reqflow
  checkpointer: # where to save checkpoints
    dirpath: ./ckpts/${experiment.wandb.project}/${experiment.wandb.name}/${now:%Y-%m-%d}_${now:%H-%M-%S}
    save_last: True
    save_top_k: -1
  trainer:
    accumulate_grad_batches: 32