defaults:
  - _default
  - _self_

data:
  dataset: scope
  rectify: False

  sampler:
    max_batch_size: 128
    max_num_res_squared: 500000

experiment:
  is_training: True
  debug: False
  num_devices: 1
  warm_start: null
  warm_start_cfg_override: True
  resume_cfg_path: null
  resume_ckpt_path: null
  resume: False
  training:
    aux_loss_t_pass: 0.25
  wandb:
    name: reqflash_train_scope_base
    project: reqflash
  checkpointer: # where to save checkpoints
    dirpath: ./ckpts/${experiment.wandb.project}/${experiment.wandb.name}/${now:%Y-%m-%d}_${now:%H-%M-%S}
    save_last: True
    save_top_k: -1